### ISSUE TITLE
Multiple Issues with refinery/Mixer

### ISSUE THREAD

**Issue by Darkere** [SilentChaos512/Silents-Mechanisms#41]
- [x]  Refinery and mixer allow fluid extraction from the input slot
- [x]  Ethane/polyethylene cannot be put into a bucket
- [x]  Water renders as gray inside the mixer
- [x]  Inventory Text renders over the bucket output slot in both

**Silent's Mechanisms**: 0.6.7+40
 **Silent Lib**: 4.4.0+44
**Forge**: 28.1.69
**Modpack**: Enigmatica4 0.2.0

**Comment by Discomanco** [comment]
To add:
Not sure if it's an XNet or Silents issue, but it will always attempt to pull from the first available slot (which as mentioned can be the Input slot), making getting Ethane out a pain with pipes. Same goes for the Mixer, and since it gladly accepts Oil and Diesel too, those 2 are stuck in there if you try to pull anything from the Refinery to the Mixer

**Comment by Seegras** [comment]
It's not just Xnet. I tried with a refined storage importer; and if I set a filter (for diesel, for instance) I can't pull anything from the refinery, or if I set none, everything will get imported, including the oil from the input.

**Comment by Darkere** [comment]
@Seegras an update was released around 5 days ago where the issues should have been fixed. Are you on the latest version?

**Comment by Seegras** [comment]
I just tried the update, and everything seems to work.

**Comment by Darkere** [comment]
great
