### ISSUE TITLE
Crusher not crushing Ores from Almost all the Ores Mod ?

### ISSUE THREAD

**Issue by CarlucciMods** [SilentChaos512/Silents-Mechanisms#61]
## Versions

- **Silent's Mechanisms**: Newest
- **Silent Lib**: Newest
- **Forge**: 28.1.111
- **Modpack**: My own

## Expected Behavior
 Crush all the ores

- (Description)

## Actual Behavior
 Ores just sits in machine

**Comment by SilentChaos512** [comment]
Need a log file. You probably have a mod that's screwing up the data-loading process. You should also include actual versions, not "Newest".

**Comment by CarlucciMods** [comment]
im not getting an error or anything, i just dont think your mod supports almost all the ores mod.  

SilentMechanisms-1.14.4-0.6.10+43
SilentLib-1.14.4-4.4.0+44

for example, almost all the ores has an ORE named Limonite when smelted in a normal furnace makes 1 iron, as it should, but when i add it to the crusher to get 2 crushed iron...its just sits there which tells me its the ore is not supported...anyway we can fix this...see video in next post

**Comment by CarlucciMods** [comment]
https://vimeo.com/383209054

**Comment by CarlucciMods** [comment]
i even tried to go into your mod and i made this but it wouldnt load. haha..never ask a starbound modder to do anything with MC>
[iron_chunks_from_limonite.zip](https://github.com/SilentChaos512/Silents-Mechanisms/files/4028840/iron_chunks_from_limonite.zip)

**Comment by SilentChaos512** [comment]
Oh, didn't realize you were talking about a specific mod. I'm guessing limonite is not tagged as an iron ore, so the recipe doesn't work. Might be best to bring it up with them, see how they want to handle things. It's possible (and easy) for other mods to add crusher recipes. It's as simple as creating data packs.

Your recipe points to a tag that doesn't exist. You could try `"item": "almostalltheores:limonite_ore"` (or whatever the item ID is).

**Comment by CarlucciMods** [comment]
ok sent them a request, in the mean time i did find this in there mod > assets\almostalltheores\blockstates\limonite.json and inside it was {
    "variants": {
        "": {
            "model": "almostalltheores:block/limonite"
        }
    }
}

is this the tag ?

**Comment by SilentChaos512** [comment]
No, that's the blockstate file, it's related to models. Anything in `assets` will be client stuff like models. Tags and recipes are in `data`.

**Comment by CarlucciMods** [comment]
this was in data > loot tables > blocks . limonite json

{
    "pools": [
        {
            "entries": [
                {
                    "type": "minecraft:item", 
                    "name": "almostalltheores:limonite"
                }
            ], 
            "name": "limonite", 
            "rolls": 1
        }
    ], 
    "type": "minecraft:block"
}

**Comment by CarlucciMods** [comment]
BINGOOo !!!!! THANKS FOR YOUR HELP I GOT IT TO WORK, IM GONNA DUE ALL THE ORES FROM THIS MOD AND OTHERS THAT DONT WORK. when im done you want a zip folder of all the work ,  add it to your next release. Ill test each one ! save you the headache

**Comment by waylanderou** [comment]
Sorry guys I see I caused you some trouble... Let me explain everything.
My mod (Almost all the Ores) has a "stone age feature"  (which can be enabled or not) that provides a machine (the refiner) supposed to refine iron ores (hematite, limonite, siderite, ...) into a dust called refined iron ore and you can only smelt that dust in the furnace to make iron. That is supposed to make early game more difficult: you really feel like you are taking a big leap forward when you have iron.
Problem is: I can't tag the ores (hematite, ...) as iron because after that, you will be able to bypass the refiner step (if you have other mods like Silent's Mechanisms or anything that uses tags) even with stone age feature activated. Instead, I chosed to tag the refined iron ore dust. 
The workaround is: if you play normal, without the "stone age" stuff, you can just make refined iron ore dust by putting iron ores in your crafting grid, and then you can use this in machines and recipes from other mods.
I didn't find a better idea than this to get everything working, and I thought it would be obvious to see using JEI, but maybe I was wrong. I am going to update my mod's description soon so no one gets stuck again.

**Comment by waylanderou** [comment]
![image](https://user-images.githubusercontent.com/55812977/71923453-54bc5580-318d-11ea-9e8b-bae222ad30e0.png)

![image](https://user-images.githubusercontent.com/55812977/71923400-3f472b80-318d-11ea-9573-17912d6d0b3b.png)

Refined iron ore works fine :)

And maybe I can add some recipes for the crusher... It could be a good idea in case someone miss the information I put in my very long mod description. It could save them time and discontent. I'm probably going to do that.
